"""add department to user

Revision ID: 16e2bffc9c78
Revises: 
Create Date: 2025-05-03 18:23:34.209755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e2bffc9c78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
    sa.Column(
        'department',
        sa.String(length=100),
        nullable=False,
        server_default='Μηχανικών Η/Υ και Πληροφορικής'
    )
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('department')

    # ### end Alembic commands ###
