"""Add original_text and edit fields to Comment

Revision ID: 33537c6228b7
Revises: 74b5ffd2d98f
Create Date: 2025-08-13 21:21:41.647736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33537c6228b7'
down_revision = '74b5ffd2d98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('original_text')

    # ### end Alembic commands ###
