"""Add chat_visibility table

Revision ID: 43cd9a846542
Revises: f0765d97a024
Create Date: 2025-09-29 22:16:42.086497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43cd9a846542'
down_revision = 'f0765d97a024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_visibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('hidden_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chat_id', name='unique_user_chat')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('reported_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('report_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['reported_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('report_ibfk_4', 'user', ['reported_by'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('reported_by',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.drop_table('chat_visibility')
    # ### end Alembic commands ###
