"""Add can_help and needs_help to user_course

Revision ID: 6e71be840c8a
Revises: 963b90e0c373
Create Date: 2025-05-20 01:12:58.844439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e71be840c8a'
down_revision = '963b90e0c373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_help', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('needs_help', sa.Boolean(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_course', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('needs_help')
        batch_op.drop_column('can_help')

    # ### end Alembic commands ###
