"""Add ON DELETE CASCADE to favorite.note_id

Revision ID: 9073dfc0db34
Revises: c51f20b850fa
Create Date: 2025-09-22 03:41:35.035676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9073dfc0db34'
down_revision = 'c51f20b850fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('favorite_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'note', ['note_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_ibfk_1', 'note', ['note_id'], ['id'])
        batch_op.create_foreign_key('favorite_ibfk_2', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
