"""Add reset_at to chat_visibility

Revision ID: bc4a9a8c6643
Revises: 43cd9a846542
Create Date: 2025-09-29 23:33:52.228707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc4a9a8c6643'
down_revision = '43cd9a846542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_visibility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('reported_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('report_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['reported_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('report_ibfk_4', 'user', ['reported_by'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('reported_by',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('chat_visibility', schema=None) as batch_op:
        batch_op.drop_column('reset_at')

    # ### end Alembic commands ###
