"""Add ON DELETE CASCADE to comment.note_id

Revision ID: c51f20b850fa
Revises: 88c02f2b591e
Create Date: 2025-09-22 03:39:19.933459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51f20b850fa'
down_revision = '88c02f2b591e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'note', ['note_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_ibfk_1', 'note', ['note_id'], ['id'])

    # ### end Alembic commands ###
