"""Add ON DELETE CASCADE to note_review.note_id

Revision ID: d4443a7afc83
Revises: 9073dfc0db34
Create Date: 2025-09-22 03:42:46.357478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4443a7afc83'
down_revision = '9073dfc0db34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_review', schema=None) as batch_op:
        batch_op.drop_constraint('note_review_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['reviewer_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('note_review_ibfk_2', 'user', ['reviewer_id'], ['id'])

    # ### end Alembic commands ###
