"""Add semester to user_course

Revision ID: e4bd0d38be1a
Revises: bc4a9a8c6643
Create Date: 2025-09-30 03:46:18.408797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4bd0d38be1a'
down_revision = 'bc4a9a8c6643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('semester',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint('report_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['reported_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('report_ibfk_4', 'user', ['reported_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('semester',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
